name: Run tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - uses: ZenVoich/setup-mops@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install mops packages
        run: mops install
      - name: test
        run: |
            npm install
            npm run replica:no-delay
            npm run test
